# This pipeline "header" defines a pipeline which will build and test a Tracim pull-request.
# It requires a ((github-webhook-token)) and a ((github-access-torken)) variables when used.
# It should be concatenated with "build-jobs.yml" to produce a complete pipeline.

## YAML definitions re-used in plans
definitions:
  main_python_version: &main_python_version "3.9.6"
  python_versions: &python_versions ["3.7.11", "3.8.11", "3.9.6"]
  databases: &databases ["sqlite", "postgresql"]

# plan step to put the current job name as pending in github's PR
pending_status_notification: &pending_status_notification
  put: tracim-status-update
  resource: tracim-source
  inputs: [tracim-source]
  params: {path: tracim-source, status: pending, context: $BUILD_JOB_NAME}
  get_params: {skip_download: true}

# sync job statuses as success/failure/error in github's PR.
status_notifications: &status_notifications
  on_success:
    put: tracim-source
    inputs: [tracim-source]
    params: {path: tracim-source, status: success, context: $BUILD_JOB_NAME}
    get_params: {skip_download: true}
  on_failure:
    put: tracim-source
    inputs: [tracim-source]
    params: {path: tracim-source, status: failure, context: $BUILD_JOB_NAME}
    get_params: {skip_download: true}
  on_abort:
    put: tracim-source
    inputs: [tracim-source]
    params: {path: tracim-source, status: error, context: $BUILD_JOB_NAME}
    get_params: {skip_download: true}
## END YAML definitions


resource_types:
- name: tracim-source
  type: registry-image
  source:
    repository: aoldershaw/github-pr-resource
- name: abort-running-builds
  type: registry-image
  source:
    repository: algooci/abort-running-builds-resource


resources:
# the github's tracim-source
- name: tracim-source
  type: tracim-source
  check_every: 30s
  # TODO - S.G. - 2021/08/02
  # The token is not used as one webhook would have to be created PER PR in github.
  # This could be automated, but is not so easy.
  webhook_token: ((github-webhook-token))
  source:
    repository: tracim/tracim
    access_token: ((github-access-token))
    number: ((number))
- name: test-image
  type: registry-image
  source:
    repository: algooci/tracim
# resource used to abort the running builds before starting our test jobs
- name: abort-running-builds
  type: abort-running-builds
  source:
    username: ((concourse-bot-user))
    password: ((concourse-bot-password))


# Pipeline jobs:
# 1. update this pipeline if the PR's file has changed
# 2. abort any running build matching the current PR
# 3. run backend (lint -> quick tests -> full tests) checks
#    run frontend (lint + unit tests) checks
#    run end-to-end (cypress) checks
#    All of these in parallel.
# Each check has its own status in the github's PR.
jobs:
- name: reconfigure-self
  plan:
  - get: tracim-source
    timeout: 5m
    trigger: true
    params:
        list_changed_files: true

  - put: abort-running-builds

  - task: build-pipeline
    image: test-image
    vars:
      pipeline: pull-request
    file: tracim-source/concourse/tasks/build-pipeline.yml

  - set_pipeline: self
    file: pipeline/pull-request.yml
    vars:
      github-webhook-token: ((github-webhook-token))
      github-access-token: ((github-access-token))
# Shared jobs definition
# can be included/appended in a complete pipeline definition.
# It must have access to:
# 1. Tracim sources through a "tracim-source" resource
# 2. Test container image through a "test-image" resource
# 3. Github status notifications called with YAML anchors:
#    - "status_notifications" (on_success/…)
#    - "pending_status_notification" job.
# 4. a "reconfigure-self" job which takes care of updating the full pipeline
